app/urls.py
from django.urls import path
from . views import *

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('about',about, name='about'),
    path('contact',contact, name='contact'),
    path('contact',signup, name='signup'),
    path('activities',activity, name='activities')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include(('app.urls','app'),namespace='app'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from . import views

# Create your views here.

def index(request):
    return render(request, 'app/index.html')

def about(request):
    return render(request,'app/about.html')

def contact(request):
    return render(request, 'app/contact.html')

def signup(request):
    return render(request, 'app/signup.html')

def activity(request):
    return render(request, 'app/activity.html')

app/templates/app/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Belivers Glorious Ministries</title>
    <link rel="shortcut icon" href="{% static '/images/logos/BGM logo_no_bg.png' %}">
    <!-- importing an external css file -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

    <style>
        
    </style>
</head>
<body>
   <!-- NAVBAR SECTION -->
<header id="site-header">
  <nav class="navbar  navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <img src="{% static '/images/logos/BGM logo_no_bg.png' %}" width="50px">
      <a class="navbar-brand fw-bold" href="{% url 'app:index' %}">Believer Glorious Ministries</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav  mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'app:index' %}">Home</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:about' %}">About</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'app:activities' %}">Activities</a>
            </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Groups</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Glorious Men</a></li>
              <li><a class="dropdown-item" href="#">Glorious Women</a></li>
              <li><a class="dropdown-item" href="#">Glorious Youth</a></li>
            </ul>
          </li> -->
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'app:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
              <a href="{% url 'app:signup' %}">
              <button type="button" class="btn btn-secondary">Become a Member</button>
              </a>
          </li>
        </ul>
        <div class="d-flex">
          <!-- <button class="btn btn-sm btn-outline-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasTop" aria-controls="offcanvasTop"><i class="fa-solid fa-magnifying-glass"></i> Search</button> -->
        </div>
      </div>
    </div>
  </nav>

  <!-- Offcanvas Block -->
  <div class="offcanvas offcanvas-top " tabindex="-1" id="offcanvasTop" aria-labelledby="offcanvasTopLabel">
    <div class="container pt-5">
      <div class="offcanvas-header">
        <h2 class="fw-bold pb-3">Search here</h2>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <form class="position-relative" action="#" method="post">
          <input type="tel" class="form-control" id="exampleFormControlInput1" placeholder="Examples: posts, services,..">
          <button class="position-absolute top-0 end-0 border-0 bg-transparent py-2 pe-2 text-secondary" type="submit" name="search"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
      </div>
    </div>
  </div>
</header>
<!-- NAVBAR SECTION -->

  <!-- Breadcrumb Block -->
  <section class="mt-5">
    <div class="bg-light py-5">
      <div class="container">
        <div class="d-flex justify-content-between">
          <h1 class="fw-bold">Contact us @ BGM</h1>
          <nav class="pt-3" style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a class="nav-link" href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Contact</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>

  <main>
    <div class="container py-5">
      <div class="row g-5">
        <!-- Contact Information Block -->
        <div class="col-xl-6">
          <div class="row row-cols-md-2 g-4">
            <div class="aos-item" data-aos="fade-up" data-aos-delay="200">
              <div class="aos-item__inner">
                <div class="bg-light hvr-shutter-out-horizontal d-block p-3">
                  <div class="d-flex justify-content-start">
                    <i class="fa-solid fa-envelope h3 pe-2"></i>
                    <span class="h5">Email</span>
                  </div>
                  <span>info@bgpmchurch.org</span>
                </div>
              </div>
            </div>
            <div class="aos-item" data-aos="fade-up" data-aos-delay="400">
              <div class="aos-item__inner">
                <div class="bg-light hvr-shutter-out-horizontal d-block p-3">
                  <div class="d-flex justify-content-start">
                    <i class="fa-solid fa-phone h3 pe-2"></i>
                    <span class="h5">Phone</span>
                  </div>
                  <span>+234 803 732 7806</span>
                </div>
              </div>
            </div>
          </div>
          <div class="aos-item mt-4" data-aos="fade-up" data-aos-delay="600">
            <div class="aos-item__inner">
              <div class="bg-light hvr-shutter-out-horizontal d-block p-3">
                <div class="d-flex justify-content-start">
                  <i class="fa-solid fa-location-pin h3 pe-2"></i>
                  <span class="h5">Office location</span>
                </div>
                <span>30, Sijuade Str,<br>
                    By Odo-Olowu B/Stop, Ijesha Express,<br>
                    Surulere, Lagos, Nigeria.</span>
              </div>
            </div>
          </div>
          <div class="aos-item" data-aos="fade-up" data-aos-delay="800">
            <div class="mt-4 w-100 aos-item__inner">
              <iframe class="hvr-shadow" width="100%" height="345" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d336.62900772993044!2d3.3232637774544913!3d6.49635104837073!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b8f4034ac558b%3A0xbcde154abc81d40a!2sBelievers%20Glorious%20Ministry!5e0!3m2!1sen!2sng!4v1722903022775!5m2!1sen!2sng"><a href="https://www.maps.ie/distance-area-calculator.html">measure acres/hectares on map</a></iframe>
            </div>
          </div>
        </div>

        <!-- Contact Form Block -->
        <div class="col-xl-6">
          <h2 class="pb-4">Leave a message</h2>
          <div class="row g-4">
            <div class="col-6 mb-3">
              <label for="exampleFormControlInput1" class="form-label">Fname</label>
              <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="First name">
            </div>
            <div class="col-6 mb-3">
              <label for="exampleFormControlInput1" class="form-label">Lname</label>
              <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Last name">
            </div>
          </div>
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email</label>
            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="Email Address">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Phone</label>
            <input type="tel" class="form-control" id="exampleFormControlInput1" placeholder="Phone Number">
          </div>
          <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Country</label>
            <input type="tel" class="form-control" id="exampleFormControlInput1" placeholder="Country">
            <!-- <select class="form-select" aria-label="Default select example">
              <option value="1">USA</option>
              <option value="2">Non USA</option>
            </select> -->
          </div>
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Message</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>
          <button type="button" class="btn btn-dark">Send Message</button>
        </div>
      </div>
    </div>
  </main>

  <!-- Footer Block -->
  <footer id="site-footer">
    <div class="bg-success bg-opacity-25 py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-xl-3 col-sm-12">
            <h5 class="pb-3"><i class="fa-solid fa-user-group pe-1"></i> About us</h5>
            <span class="text-secondary">Believers Glorious Prayer Ministry started as just a prayer meeting, with the name, Glorious Assembly, at No.30 <a href="/about.html">READ MORE</a></span>
          </div>
          <div class="col-md-6 col-xl-3 col-sm-12">
            <h5 class="pb-3"><i class="fa-solid fa-link pe-1"></i>Links</h5>
            <ul>
              <li><a href="/index.html" class="text-decoration-none link-secondary">Home</a></li>
              <li><a href="/about.html" class="text-decoration-none link-secondary">About Us</a></li>
              <li><a href="/contact.html" class="text-decoration-none link-secondary">Contact Us</a></li>
              <li><a href="#" class="text-decoration-none link-secondary">Groups</a></li>
            </ul>
          </div>
          <div class="col-md-6 col-xl-3 col-sm-12">
            <h5 class="pb-3"><i class="fa-solid fa-location-dot pe-1"></i> Our location</h5>
            <span class="text-secondary">
                30, Sijuade Str,<br>
                By Odo-Olowu B/Stop, Ijesha Express,<br>
                Surulere, Lagos, Nigeria.<br>
            </span>
          </div>
          <div class="col-md-6 col-xl-3 col-sm-12">
            <h5 class="pb-3"><i class="fa-solid fa-paper-plane pe-1"></i> Stay updated</h5>
            <form>
              <input type="text" class="w-100 mb-2 form-control" name="" placeholder="Email ID">
              <button class="w-100 btn btn-dark">Subscribe now</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="bg-dark py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-sm-12">
            <ul class="list-inline mb-0">
              <li class="list-inline-item"><a class="btn btn-outline-secondary" href="#"><i class="fa-solid fa-brands  fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a class="btn btn-outline-secondary" href="#"><i class="fa-solid fa-brands fa-youtube"></i></a></li>
              <li class="list-inline-item"><a class="btn btn-outline-secondary" href="#"><i class="fa-brands fa-twitter"></i></a></li>
              <!-- <li class="list-inline-item"><a class="btn btn-outline-secondary" href="#"><i class="fa-brands fab fa-linkedin-in"></i></a></li> -->
              <!-- <li class="list-inline-item"><a class="btn btn-outline-secondary" href="#"><i class="fa-brands fab fa-github"></i></a></li> -->
            </ul>
          </div>
          <div class="col-md-6 col-sm-12"><span class="text-secondary pt-1 float-md-end float-sm-start">&copy; 2024 Believers Glorious Ministries. All Rights Reserved.</span></div>
        </div> 
      </div>
    </div>
  </footer>


    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <title>Believers Glorious Ministries</title>
    <link rel="shortcut icon" href="/images/logos/BGM logo_no_bg.png">
    <!-- importing an external css file -->
    <link rel="stylesheet" type="text/css" href="reg.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
</head>
<body class="body">
  <!-- NAVBAR SECTION -->
<header id="site-header">
  <nav class="navbar  navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <img src="{% static '/images/logos/BGM logo_no_bg.png' %}" width="50px">
      <a class="navbar-brand fw-bold" href="{% url 'app:index' %}">Believer Glorious Ministries</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav  mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'app:index' %}">Home</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:about' %}">About</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'app:activities' %}">Activities</a>
            </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Groups</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Glorious Men</a></li>
              <li><a class="dropdown-item" href="#">Glorious Women</a></li>
              <li><a class="dropdown-item" href="#">Glorious Youth</a></li>
            </ul>
          </li> -->
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'app:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
              <a href="{% url 'app:signup' %}">
              <button type="button" class="btn btn-secondary">Become a Member</button>
              </a>
          </li>
        </ul>
        <div class="d-flex">
          <!-- <button class="btn btn-sm btn-outline-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasTop" aria-controls="offcanvasTop"><i class="fa-solid fa-magnifying-glass"></i> Search</button> -->
        </div>
      </div>
    </div>
  </nav>

  <!-- Offcanvas Block -->
  <div class="offcanvas offcanvas-top " tabindex="-1" id="offcanvasTop" aria-labelledby="offcanvasTopLabel">
    <div class="container pt-5">
      <div class="offcanvas-header">
        <h2 class="fw-bold pb-3">Search here</h2>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <form class="position-relative" action="#" method="post">
          <input type="tel" class="form-control" id="exampleFormControlInput1" placeholder="Examples: posts, services,..">
          <button class="position-absolute top-0 end-0 border-0 bg-transparent py-2 pe-2 text-secondary" type="submit" name="search"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
      </div>
    </div>
  </div>
</header>
<!-- NAVBAR SECTION -->



    <section class="vh-100 gradient-custom mt-3 pt-3">
        <div class="container py-5 h-100">
          <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
              <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                <div class="card-body p-4 p-md-5">
                  <h3 class="mb-4 pb-2 pb-md-0 mb-md-5" style="text-align: center;">Become a Member</h3>
                  <form class="row g-3 needs-validation" novalidate>
                    <div class="col-md-4">
                      <label for="validationCustom01" class="form-label">First name</label>
                      <input type="text" class="form-control" id="validationCustom01" required>
                      <div class="valid-feedback">
                        Looks good!
                      </div>
                    </div>
                    <div class="col-md-4">
                      <label for="validationCustom02" class="form-label">Last name</label>
                      <input type="text" class="form-control" id="validationCustom02" required>
                      <div class="valid-feedback">
                        Looks good!
                      </div>
                    </div>
                    <div class="col-md-4">
                      <label for="validationCustomUsername" class="form-label">Phone</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">+</span>
                        <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
                        <div class="invalid-feedback">
                          Please enter a valid phone number
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <label for="validationCustom03" class="form-label">Email address</label>
                      <input type="text" class="form-control" id="validationCustom03" required>
                      <div class="invalid-feedback">
                        Please enter a valid email address
                      </div>
                    </div>
                    <div class="col-md-3">
                      <label for="validationCustom04" class="form-label">Marital Status</label>
                      <select class="form-select" id="validationCustom04" required>
                        <option selected disabled value="">Choose...</option>
                        <option>Single</option>
                        <option>Married</option>
                      </select>
                      <div class="invalid-feedback">
                        Please choose a marital status
                      </div>
                    </div>
                    <div class="col-md-3">
                      <label for="validationCustom05" class="form-label">Gender</label>
                      <div class="form-check">
                        <input type="radio" class="form-check-input" id="validationFormCheck2" name="radio-stacked" required>
                        <label class="form-check-label" for="validationFormCheck2">Male</label>
                      </div>
                      <div class="form-check mb-3">
                        <input type="radio" class="form-check-input" id="validationFormCheck3" name="radio-stacked" required>
                        <label class="form-label" for="validationFormCheck3">Female</label>
                        <div class="invalid-feedback">Select a gender</div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <label for="validationCustom03" class="form-label">Birthday</label>
                      <input type="date" class="form-control" id="validationCustom03" required>
                      <div class="invalid-feedback">
                        Please enter Your date of birth
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary" type="submit">Submit Request</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    

    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="reg.js"></script>
</body>
</html>